[versions]
## Android gradle plugin
androidGradlePlugin = "8.13.2"

# https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md
androidDesugarJdkLibs = "2.1.5"

## AndroidX
# https://developer.android.com/jetpack/androidx/releases/core
androidxCore = "1.17.0"
# https://developer.android.com/jetpack/androidx/releases/appcompat
androidxAppCompat = "1.7.1"
# https://developer.android.com/jetpack/androidx/releases/lifecycle
androidxLifecycle = "2.10.0"
# https://developer.android.com/jetpack/androidx/releases/activity
androidxActivity = "1.12.4"
# https://developer.android.com/jetpack/androidx/releases/datastore
androidxDatastore = "1.2.0"
# https://developer.android.com/jetpack/androidx/releases/glance
androidxGlance = "1.1.1"
coilCompose = "2.7.0"
credentials = "1.6.0-rc01"
desugar_jdk_libs = "2.1.5"
espressoCore = "3.5.1"
firebaseBom = "34.9.0"
glanceExperimentalTools = "0.2.2"
# https://developer.android.com/jetpack/androidx/releases/profileinstaller
googleid = "1.2.0"
junit = "1.1.5"
materialIconsExtended = "1.7.8"
oauth = "5.11.1"
paymentSdkAndroid = "0.1.15"
playServicesAuth = "21.5.0"
profileinstaller = "1.4.1"
# https://developer.android.com/jetpack/androidx/releases/benchmark
baselineprofile = "1.4.1"

## Compose
# https://developer.android.com/develop/ui/compose/bom/bom-mapping
androidxComposeBom = "2026.02.00"
# https://developer.android.com/jetpack/androidx/releases/navigation
androidxComposeNavigation = "2.9.6"
# https://developer.android.com/jetpack/androidx/releases/compose-material3
androidxComposeMaterial3 = "1.4.0"

# https://github.com/skydoves/landscapist
landscapist = "2.9.5"
# https://github.com/valentinilk/compose-shimmer
composeShimmer = "1.3.3"

## Kotlin Symbol Processing
# https://github.com/google/ksp/
ksp = "2.2.21-2.0.4"

## Hilt
# https://github.com/google/dagger/releases
hilt = "2.57.2"
# https://developer.android.com/jetpack/androidx/releases/hilt
hiltNavigationCompose = "1.3.0"

## Network
# okhttp
# # https://square.github.io/okhttp/
okhttp = "5.3.2"
# Retrofit
# # https://github.com/square/retrofit
retrofit = "3.0.0"

## Kotlin
# https://github.com/JetBrains/kotlin
kotlin = "2.2.21"
# https://github.com/Kotlin/kotlinx.serialization
kotlinxSerializationJson = "1.10.0"
# https://github.com/Kotlin/kotlinx-datetime/releases
kotlinxDatetime = "0.7.1"
# https://github.com/Kotlin/kotlinx.collections.immutable
kotlinxImmutable = "0.4.0"

## Coroutine
# https://github.com/cashapp/turbine
roomRuntime = "2.8.4"
turbine = "1.2.1"
# https://github.com/Kotlin/kotlinx.coroutines
coroutine = "1.10.2"

## license
# https://developers.google.com/android/guides/opensource
ossLicenses = "17.4.0"
ossLicensesPlugin = "0.10.10"

## Test
# https://github.com/junit-team/junit4
junit4 = "4.13.2"
# https://mvnrepository.com/artifact/org.junit.vintage/junit-vintage-engine
junitVintageEngine = "6.0.2"
# https://developer.android.com/jetpack/androidx/releases/test-uiautomator
uiAutomator = "2.3.0"
androidxTestRunner = "1.7.0"
# https://developer.android.com/jetpack/androidx/releases/benchmark
benchmarkMacroJunit4 = "1.4.1"

# # https://developer.android.com/jetpack/androidx/releases/test
androidxTestExt = "1.3.0"
androidxEspresso = "3.7.0"
# # https://github.com/takahirom/roborazzi
roborazzi = "1.59.0"
# https://github.com/robolectric/robolectric/releases
robolectric = "4.16.1"
# https://kotest.io/
kotest = "6.1.3"
# https://github.com/detekt/detekt
detekt = "1.23.8"
# https://github.com/twitter/compose-rules
detektTwitterComposeRule = "0.0.26"
# https://mockk.io/
mockk = "1.14.9"
# https://github.com/mockito/mockito
test-mockito = "5.21.0"
# https://github.com/mockito/mockito-kotlin
test-mockito-kotlin = "6.2.3"
# https://github.com/mannodermaus/android-junit5
test-junit5-plugin = "2.0.1"
# https://github.com/junit-team/junit5
test-junit5 = "6.0.2"
material = "1.13.0"
lifecycleRuntimeKtx = "2.10.0"
datastoreCore = "1.2.0"
identityAndroidLegacy = "202411.1"
v2All = "2.22.0"
ui = "1.10.3"
foundation = "1.10.3"
firebaseFirestoreKtx = "26.0.2"
firebaseAuthKtx = "24.0.1"

androidx-core-splashscreen = "1.2.0"

placeholder = "1.0.2"
firebaseComponents = "19.0.1"
hiltWork = "1.3.0"
hiltCommon = "1.3.0"
workRuntimeKtx = "2.11.1"
lifecycleService = "2.10.0"
lifecycleProcess = "2.10.0"
lifecycleViewmodelKtx = "2.10.0"
foundationVersion = "1.10.3"
runtimeAnnotation = "1.10.3"
androidxFoundation = "1.10.3"
androidxFoundationVersion = "1.10.3"
cameraCore = "1.5.3"
uiToolingPreviewAndroid = "1.10.3"
roomKtx = "2.8.4"

nav3Core = "1.0.1"
lifecycleViewmodelNav3 = "2.10.0"
kotlinSerialization = "2.2.21"
kotlinxSerializationCore = "1.10.0"
material3AdaptiveNav3 = "1.3.0-alpha08"

[libraries]

androidx-compose-material3-window-size-class1 = { module = "androidx.compose.material3:material3-window-size-class" }
androidx-espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit-v115 = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3Core" }
androidx-navigation3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3Core" }

# Optional add-on libraries
androidx-lifecycle-viewmodel-navigation3 = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycleViewmodelNav3" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }
androidx-material3-adaptive-navigation3 = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation3", version.ref = "material3AdaptiveNav3" }


android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
desugar_jdk_libs-v212 = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
google-firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }

androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiAutomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }

androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxComposeNavigation" }
androidx-compose-navigation-test = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxComposeNavigation" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

oauth = { module = "com.navercorp.nid:oauth", version.ref = "oauth" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
payment-sdk-android = { module = "com.github.tosspayments:payment-sdk-android", version.ref = "paymentSdkAndroid" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }

landscapist-bom = { group = "com.github.skydoves", name = "landscapist-bom", version.ref = "landscapist" }
landscapist-coil = { group = "com.github.skydoves", name = "landscapist-coil" }
landscapist-placeholder = { group = "com.github.skydoves", name = "landscapist-placeholder" }
landscapist-animation = { group = "com.github.skydoves", name = "landscapist-animation" }

compose-shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "composeShimmer" }

androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-core-splashscreen" }

junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
junit-vintage-engine = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junitVintageEngine" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }
roborazziRule = { module = "io.github.takahirom.roborazzi:roborazzi-junit-rule", version.ref = "roborazzi" }
roborazziCompose = { module = "io.github.takahirom.roborazzi:roborazzi-compose", version.ref = "roborazzi" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
inject = "javax.inject:javax.inject:1"
kotest-runner = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

compose-placeholder = { module = "com.revenuecat.purchases:placeholder", version.ref = "placeholder" }

## Test mockito
test-mockito = { group = "org.mockito", name = "mockito-core", version.ref = "test-mockito" }
test-mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "test-mockito-kotlin" }

## Test junit 5
test-junit5 = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "test-junit5" }
test-junit5-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "test-junit5" }
test-junit5-vintage = { group = "org.junit.jupiter", name = "junit-vintage-engin", version.ref = "test-junit5" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutine" }

oss-licenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "ossLicenses" }

# verify
v2-all = { module = "com.kakao.sdk:v2-all", version.ref = "v2All" }
verify-detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
verify-twitter-detektComposeRule = { module = "com.twitter.compose.rules:detekt", version.ref = "detektTwitterComposeRule" }

# plugin
verify-detektPlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastore" }
oss-licenses-plugin = { group = "com.google.android.gms", name = "oss-licenses-plugin", version.ref = "ossLicensesPlugin" }
plugin-kotlin-serializationPlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
plugin-android-junit5 = { group = "de.mannodermaus.gradle.plugins", name = "android-junit5", version.ref = "test-junit5-plugin" }

androidx-glance = { group = "androidx.glance", name = "glance", version.ref = "androidxGlance" }
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "androidxGlance" }
glance-tools-appwidget-host = { group = "com.google.android.glance.tools", name = "appwidget-host", version.ref = "glanceExperimentalTools" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-datastore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastoreCore" }
identity-android-legacy = { group = "com.android.identity", name = "identity-android-legacy", version.ref = "identityAndroidLegacy" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-components = { group = "com.google.firebase", name = "firebase-components", version.ref = "firebaseComponents" }
androidx-hilt-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltWork" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version = "1.3.0" }
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hiltCommon" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundationVersion" }
androidx-compose-runtime-annotation = { group = "androidx.compose.runtime", name = "runtime-annotation", version.ref = "runtimeAnnotation" }
androidx-compose-foundation-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidxFoundation" }
androidx-compose-foundation-foundation2 = { group = "androidx.compose.foundation", name = "foundation", version.ref = "androidxFoundationVersion" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraCore" }
androidx-compose-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }



[bundles]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
verify-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
roborazzi-plugin = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }

# Plugins defined by this project
dailydango-android-application = { id = "bhst.dailydango.android.application", version = "unspecified" }

dailydango-android-library = { id = "bhst.dailydango.android.library", version = "unspecified" }
dailydango-android-feature = { id = "bhst.dailydango.android.feature", version = "unspecified" }
dailydango-android-compose = { id = "bhst.dailydango.android.compose", version = "unspecified" }
dailydango-android-hilt = { id = "bhst.dailydango.android.hilt", version = "unspecified" }

dailydango-kotlin-library = { id = "bhst.dailydango.kotlin.library", version = "unspecified" }
dailydango-kotlin-library-serialization = { id = "bhst.dailydango.kotlin.library.serialization", version = "unspecified" }

